### ISSUE TITLE
Would you mind not calling it datathon as it's very generic (was announced in class). Thank you! 

### ISSUE THREAD

**Issue by resteorts** [namanagar/Rmasters#1]

**Comment by namanagar** [comment]
I was thinking it would make more sense to rename the repo based on the name of the project/dataset we end up working with/something relevant to the work we do on the day of

**Comment by resteorts** [comment]
Great idea and you can always rename the repo after the event

On Oct 19, 2018, at 12:37 PM, Naman Agarwal <notifications@github.com<mailto:notifications@github.com>> wrote:


I was thinking it would make more sense to rename the repo based on the name of the project/dataset we end up working with/something relevant to the work we do on the day of
